USE [Marina]
GO

/****** Object:  Table [dbo].[Routes]    Script Date: 25.04.2022 12:51:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Routes](
	[ID_ROUTE] [int] NOT NULL,
	[ID_LINE] [nchar](10) NOT NULL,
	[ID_VESSEL] [nchar](10) NOT NULL,
 CONSTRAINT [PK_Routes] PRIMARY KEY CLUSTERED 
(
	[ID_ROUTE] ASC,
	[ID_LINE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Routes]  WITH CHECK ADD  CONSTRAINT [FK_Routes_Lines] FOREIGN KEY([ID_LINE])
REFERENCES [dbo].[Lines] ([ID_LINE])
GO

ALTER TABLE [dbo].[Routes] CHECK CONSTRAINT [FK_Routes_Lines]
GO

ALTER TABLE [dbo].[Routes]  WITH CHECK ADD  CONSTRAINT [FK_Routes_Vessels] FOREIGN KEY([ID_VESSEL])
REFERENCES [dbo].[Vessels] ([ID_VESSEL])
GO

ALTER TABLE [dbo].[Routes] CHECK CONSTRAINT [FK_Routes_Vessels]
GO

